### ISSUE TITLE
maybe you could consider surpporting cross paltform

### ISSUE THREAD

**Issue by qicosmos** [thrill/thrill#120]
I think this project could be more universal, surpport win and linux.
the network can be implement by boost.asio which surpport cross platform.

It would be very regrettable if modern c++ has no Big Data batch computations framwork, howerver thrill
appeared, the future is bright.
i'm very intresting in this project,  i want to join in.

**Comment by bingmann** [comment]
Thrill already works on MacOSX and Windows. Except for the network layer on Windows. But one does not need asio for that, only apply a few fixups for Microsoft's WinSock API.
