### ISSUE TITLE
Add document to show how developer can use the API

### ISSUE THREAD

**Issue by jackyq2015** [thrill/thrill#121]
Include following

- How to setup a cluster 

- How to code, compile, build and run a simple application

**Comment by lorenzhs** [comment]
Yeah there's a lot of documentation work still to be done - for now, the [Doxygen documentation](http://i10login.iti.kit.edu/thrill-doxygen/) provides some overview of the architecture and reference, but a "getting started" documentation would be nice. For now, [WordCount](https://github.com/thrill/thrill/tree/master/examples/word_count) can serve as an example maybe?

**Comment by jackyq2015** [comment]
Before dive into Doxygen and look into the detail, it would be helpful if have some step by step procedure to setup a cluster and run the sample application. Or a shell script to launch a basic cluster locally to demonstrate.

**Comment by lorenzhs** [comment]
You can just execute the binary, it will use all cores of your machine and simulate two hosts. @bingmann is currently working on the documentation, so stay tuned.

**Comment by bingmann** [comment]
The doxygen documentation now has a nice k-means tutorial.
