### ISSUE TITLE
libs3 feature detection is broken

### ISSUE THREAD

**Issue by lorenzhs** [thrill/thrill#130]
Configuring fails if libcurl-dev (or another libs3 dependency) isn't installed or the submodule isn't there. It should fall back to not using S3 in this case.

**Comment by bingmann** [comment]
Please submit a patch.

**Comment by lorenzhs** [comment]
You broke it. You fix it!

**Comment by bingmann** [comment]
Not broken. Install libcurl-dev / libcurl4-openssl-dev.

**Comment by lorenzhs** [comment]
libs3 is not required though. This means that Thrill fails to build in its default configuration without these libraries. So it's broken.

**Comment by bingmann** [comment]
Please submit a patch.

**Comment by lorenzhs** [comment]
Are you a Markov chain? I don't know cmake.
