### ISSUE TITLE
Suggest support windows

### ISSUE THREAD

**Issue by qicosmos** [thrill/thrill#134]
Hi，i hope thrill can surpport windows. The benefits are not just surpport one more paltform but alse can improve the develop efficiency with msvc.
I think you can replace the current network library with a cross platform network libary, and then thrill will surpport windows.
I have devleloped an easy to use and high performance rpc libary with modern c++, includes request/response and pub/sub mode.
Here is the introduction: https://github.com/topcpporg/rest_rpc/wiki/English
If you want use rpc, I can do some help to do this work.

**Comment by bingmann** [comment]
Thrill already supports windows to a degree, mainly for development.
We have a "mock" network layer which is platform independent. And the tcp layer only needs a few small adjustments to the Winsock-Stack.
Your RPC library looks great.
Windows CI-Builds of Appveyor: https://ci.appveyor.com/project/bingmann/thrill/history
