### ISSUE TITLE
Implicit fallthrough in hash.hpp

### ISSUE THREAD

**Issue by SDEagle** [thrill/thrill#170]
GCC 7 complains about a bunch of implicit fallthroughs in `hash.hpp` in the switch beginning at line `137`. I think the fallthroughs are intentional but I don't know or understand that code, so it would be nice if somebody could add `__attribute__((fallthrough));` to fix the warnings if the fallthroughs are indeed intended.

**Comment by lorenzhs** [comment]
See my comments in https://github.com/tlx/tlx/pull/2

**Comment by SDEagle** [comment]
Aw 🙈 should have done some more homework apparently... so should we add flags to disable the warnings to the `CMakeLists.txt` then? On the other hand C++17 is now formally approved and both Clang (5) and GCC 7 seem to support the standard completely. So it might make sense at some point to move on to 17...

**Comment by lorenzhs** [comment]
I think `-Wno-implicit-fallthrough` would be best for now. I've moved my fork of Thrill to C++17 (`if constexpr(/* foo */)` :heart_eyes:`) but I'm not sure whether the thrill project should move just yet. It needs tooling support on clusters etc...

**Comment by bingmann** [comment]
Guys, guys ... just use a macro. similar to
https://github.com/tlx/tlx/blob/master/tlx/define/attribute_format_printf.hpp
there is little other choice.

**Comment by lorenzhs** [comment]
Ugh using macros is awfully ugly and annoying if you can just disable the warning without causing much harm.

**Comment by bingmann** [comment]
Fixed using
https://github.com/tlx/tlx/blob/master/tlx/define/attribute_fallthrough.hpp
