### ISSUE TITLE
It's a pitty to see the project dieing

### ISSUE THREAD

**Issue by zhanglistar** [thrill/thrill#191]

**Comment by lorenzhs** [comment]
Creating a whiny issue isn't going to fix it, and I don't see any contributions from you. Respectfully, you're not helping.

**Comment by BestP2P** [comment]
so, it is alive? i hope so

**Comment by zhanglistar** [comment]
> Creating a whiny issue isn't going to fix it, and I don't see any contributions from you. Respectfully, you're not helping.

Yes, you are right. I will do some help.
