### ISSUE TITLE
the param's value in GroupByFunction  of GroupByKey is not match

### ISSUE THREAD

**Issue by zyxgis** [thrill/thrill#201]
my code is

```
auto keyExtractorFunction = [](const IndexFeature &p) -> int64_t { return p.first; };
auto groupFunction = [all = std::vector<IndexFeature> ()](auto &r, const int64_t &index) mutable -> FeatureGroup {
	all.clear();
	while (r.HasNext())
	{
		all.push_back(r.Next());
	}
	return std::make_pair(index, all);
};
//
auto groupSourceDIA = featureSourceDIA.GroupByKey<FeatureGroup>(keyExtractorFunction, groupFunction).Keep(2);
//
std::vector<FeatureGroup> groupSourceList = groupSourceDIA.AllGather();
for_each(groupSourceList.begin(), groupSourceList.end(), [](FeatureGroup &featureGroup) {
	std::cout << featureGroup.first;
	for_each(featureGroup.second.begin(), featureGroup.second.end(), [](IndexFeature &indexFeature) {
	  std::cout << "," << indexFeature.first;
	});
	std::cout << std::endl;
});
```
  ----------------------------------------------------------------------------
the output is

1105546764,1105481228,1105481228,1105481228,1105481228,1105481228,1105481228
1105612296,1105546764,1105546764,1105546764,1105546764,1105546764,1105546764
1105612300,1105612296,1105612296,1105612296,1105612296,1105612296,1105612296
1105677832,1105612300,1105612300,1105612300,1105612300,1105612300,1105612300
1105677836,1105677832,1105677832,1105677832,1105677832,1105677832,1105677832
1105743368,1105677836,1105677836,1105677836,1105677836,1105677836,1105677836
1105743372,1105743368,1105743368,1105743368,1105743368,1105743368,1105743368
1105808904,1105743372
1105874436,1105808904,1105808904,1105808904,1105808904,1105808904,1105808904
1105874440,1105874436,1105874436,1105874436
1105939976,1105874440,1105874440,1105874440,1105874440,1105874440,1105874440
1106005512,1105939976,1105939976,1105939976,1105939976,1105939976,1105939976
1106071048,1106005512,1106005512,1106005512,1106005512,1106005512,1106005512
1106071048,1106071048,1106071048,1106071048,1106071048,1106071048,1106071048
1105481225,1105415689
1105546761,1105481225,1105481225,1105481225,1105481225,1105481225,1105481225
1105612297,1105546761,1105546761,1105546761,1105546761,1105546761,1105546761
1105612301,1105612297,1105612297,1105612297,1105612297,1105612297,1105612297
1105677833,1105612301

**Comment by zyxgis** [comment]
the first column is not equal to the other columns

**Comment by BestP2P** [comment]
const int64_t &index, this will change	
return std::make_pair(index, all); don't do this, index should use before while loop, after the while loop, don't use the key!

**Comment by zyxgis** [comment]
> const int64_t &index, this will change
> return std::make_pair(index, all); don't do this, index should use before while loop, after the while loop, don't use the key!

thank you very much
