### ISSUE TITLE
Does not compile with clang if using TBB's concurrent bounded queue

### ISSUE THREAD

**Issue by lorenzhs** [thrill/thrill#88]
See https://gist.github.com/lorenzhs/8da5894794c80c000862 for log. Compiles fine with g++.

**Comment by lorenzhs** [comment]
Updating TBB to 4.4 as suggested in https://gist.github.com/lorenzhs/8da5894794c80c000862#gistcomment-1584468 does not solve this.

**Comment by lorenzhs** [comment]
I think this is a bug in how TBB detects the presence of variadic template support. From their feature detection code:
```cpp
//TODO: these options need to be rechecked
/** on OS X* the only way to get C++11 is to use clang. For library features (e.g. exception_ptr) libc++ is also
 *  required. So there is no need to check GCC version for clang**/
```

**Comment by lorenzhs** [comment]
Closing as upstream bug.

**Comment by bingmann** [comment]
I use TBB 4.3.20150611 just fine.

**Comment by lorenzhs** [comment]
You're using libc++, not libstdc++, so the issue does not affect you.
