### ISSUE TITLE
Statistics for StageBuilder and data/net Subsystem

### ISSUE THREAD

**Issue by bingmann** [thrill/thrill#96]
We need much more statistical output and aggregation.
a) how does StageBuilder run the graph?, which node takes how much time?, which subnodes are run in this stage?
b) each Node's resources must be monitorable: how many Files does the Node use? how many items/bytes were put into it? how many Streams did it use? What was the transfer speed of the streams?
c) we need individual and overall aggregated stats to find straglers
d) we need a time line of how many data blocks exist in the system, maybe even which files they belong to. -> nice plots over time

**Comment by alexnoe** [comment]
Should be fixed.

**Comment by bingmann** [comment]
Nope. Wrong issue.

**Comment by alexnoe** [comment]
Heh, oops. Sorry.

**Comment by bingmann** [comment]
Ideas from whiteboard
![2015-10-29 12 46 34](https://cloud.githubusercontent.com/assets/2604907/10817699/e600b7c0-7e3b-11e5-87d6-efbbc70485df.jpg)
